views:
  - name: customer_credit_insights
    description: "This view provides insights into customer credit risk, transactions, and credit behavior."
    public: true
    meta:
      title: Customer Credit Insights
      tags:
        - DPDomain.CreditCardInsights
      metric:
        expression: "*/45 * * * *"
        timezone: "UTC"
        window: "day"

    tables:
      - join_path: customer_data
        prefix: true
        includes: 
          - Risk_Category  # measure
          - Avg_Utl_Ratio    # measure columns
          - Total_Rev_Bal
          - Delin_Acc
          - Cd_Limit
          - Total_Trns_Amt
          - Client_Num        # Groupby column
          - Week_Start_Date   # Timestamp