views:
  - name: risky_customer_insights
    description: "This view provides insights into customer credit risk, transactions, and credit behavior."
    public: true
    meta:
      title: Risky Customer Insights
      tags:
        - DPDomain.Analysis
        - DPDomain.CreditCardInsights
      metric:
       expression: "*/45 * * * *"
       timezone: "UTC"
       window: "day"

    tables:
      - join_path: customer_data
        prefix: true
        includes: 
          - risky_customer_percentage  # measure
          - Avg_Utilization_Ratio    # measure columns
          - Total_Revolving_Bal
          - Delinquent_Acc
          - Credit_Limit
          - Total_Trans_Amt
          - Client_Num        # Groupby column
          - Week_Start_Date   # Timestamp